layout_spectrum: 0.1852635
typography_spectrum: 0.6987761
color:
  saturation: 0.2026763
  lightness: 0.7611276
  brandStrength: 1
  brandColors:
    - '#2F3142'
    - '#B5C7D8'
    - '#6E88A3'
    - '#FFFFFF'
    - '#005D01'
  rhythmicContrast: 0.3681908
name: David Sebastian Buus
